---
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
    - "bundle exec rake validate lint spec SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.1
    bundler_args: --without development
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true STRICT_VARIABLES=yes
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.3.1
    bundler_args: --without development
    dist: trusty
    env: BEAKER_set=ubuntu-16.04 PUPPET_INSTALL_TYPE=agent BEAKER_debug=true
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.3.1
    bundler_args: --without development
    dist: trusty
    env: BEAKER_set=centos-7 PUPPET_INSTALL_TYPE=agent BEAKER_debug=true
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.3.1
    bundler_args: --without system_tests development
    env: STRICT_VARIABLES="yes"
    script: bundle exec rake rubocop
  - rvm: 2.1.10
    bundler_args: --without system_tests development
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes
  - rvm: 2.1.10
    bundler_args: --without system_tests development
    env: PUPPET_GEM_VERSION="3.8.7"
  allow_failures:
    - env: PUPPET_GEM_VERSION="3.8.7"
notifications:
  email: false
